apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-k8s-vault
  labels:
    app: python-k8s-vault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-k8s-vault
  template:
    metadata:
      labels:
        app: python-k8s-vault
      annotations:

        instrumentation.opentelemetry.io/inject-python: 'opentelemetry/instrumentation'
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "app-python-role"
        vault.hashicorp.com/agent-inject-template-json: |
          {{- with secret "app/data/python" -}}
          {{ .Data.data | toJSON }}
          {{- end }}
    spec:
      containers:
      - name: python-k8s-vault
        image: cauanlima/python-k8s-vault:v1.0.2
        ports:
        - containerPort: 8200

---
apiVersion: v1
kind: Service
metadata:
  name: python-k8s-vault-service
  labels:
    app: python-k8s-vault
spec:
  type: NodePort  # <-- Mudei para NodePort
  selector:
    app: python-k8s-vault
  ports:
    - protocol: TCP
      port: 8000         # <-- Corrigido! Seu app FastAPI escuta na 8000, não 8200
      targetPort: 8000   # <-- Corrigido para o container também na 8000
      nodePort: 31001    # <-- Porta fixa exposta no nó

